copyright: Copyright &copy; 2023 REPENTOGON developers
edit_uri: edit/main/documentation/docs/
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/IsaacZHL/REPENTOGON
    name: REPENTOGON source code and documentation
  version:
    default: rep
    provider: mike
extra_css:
- css/custom.css
extra_javascript:
- https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js
- https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
- js/tablesort.number.min.js
- js/customJS.js
- js/jquery.mark.min.js
markdown_extensions:
- toc:
    permalink: "\u2693\uFE0E"
    toc_depth: 3
- pymdownx.highlight:
    linenums: true
- pymdownx.superfences:
    custom_fences:
    - class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
      name: mermaid
- pymdownx.inlinehilite
- pymdownx.snippets:
    check_paths: true
    url_download: true
- admonition
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
    emoji_index: !!python/name:materialx.emoji.twemoji ''
- pymdownx.tabbed:
    alternate_style: true
- attr_list
nav:
- Home: index.md
- Docs:
  - Home: index.md
  - Enums:
    - Achievement: enums/Achievement.md
    - AnnouncerVoiceMode: enums/AnnouncerVoiceMode.md
    - AutocompleteType: enums/AutocompleteType.md
    - BagOfCraftingPickup: enums/BagOfCraftingPickup.md
    - BitwiseDebugFlag: enums/BitwiseDebugFlag.md
    - BossType: enums/BossType.md
    - CameraStyle: enums/CameraStyle.md
    - CompletionType: enums/CompletionType.md
    - ConsoleFont: enums/ConsoleFont.md
    - DebugFlag: enums/DebugFlag.md
    - Dimension: enums/Dimension.md
    - DipSubType: enums/DipSubType.md
    - Ending: enums/Ending.md
    - EntityPoopVariant: enums/EntityPoopVariant.md
    - EventCounter: enums/EventCounter.md
    - ExtraHudStyle: enums/ExtraHudStyle.md
    - FadeoutTarget: enums/FadeoutTarget.md
    - FollowerPriority: enums/FollowerPriority.md
    - Giantbook: enums/Giantbook.md
    - GridPoopVariant: enums/GridPoopVariant.md
    - HealthType: enums/HealthType.md
    - ImGuiCallback: enums/ImGuiCallback.md
    - ImGuiData: enums/ImGuiData.md
    - ImGuiElement: enums/ImGuiElement.md
    - ItemAnim: enums/ItemAnim.md
    - KnifeSubType: enums/KnifeSubType.md
    - KnifeVariant: enums/KnifeVariant.md
    - Language: enums/Language.md
    - LineCheckMode: enums/LineCheckMode.md
    - MainMenu: enums/MainMenu.md
    - ModCallbacks: enums/ModCallbacks.md
    - MouseButton: enums/MouseButton.md
    - NullPickupSubType: enums/NullPickupSubType.md
    - PauseMenuStates: enums/PauseMenuStates.md
    - PedestalType: enums/PedestalType.md
    - PillCardSlot: enums/PillCardSlot.md
    - PlayerVariant: enums/PlayerVariant.md
    - PocketItemType: enums/PocketItemType.md
    - PressurePlateVariant: enums/PressurePlateVariant.md
    - ProjectileMode: enums/ProjectileMode.md
    - RetractingSpikesVariant: enums/RetractingSpikesVariant.md
    - RoomSubType: enums/RoomSubType.md
    - SlotVariant: enums/SlotVariant.md
    - StbGridType: enums/StbGridType.md
    - StbPoopSubType: enums/StbPoopSubType.md
    - StbRailVariant: enums/StbRailVariant.md
    - StbRockSubType: enums/StbRockSubType.md
    - StbTeleporterSubType: enums/StbTeleporterSubType.md
    - StbType: enums/StbType.md
    - TaintedMarksGroup: enums/TaintedMarksGroup.md
    - TeleporterVariant: enums/TeleporterVariant.md
    - WeaponModifier: enums/WeaponModifier.md
    - WispSubType: enums/WispSubType.md
    - XMLNode: enums/XMLNode.md
  - Ambush: Ambush.md
  - AnimationState: AnimationState.md
  - Camera: Camera.md
  - ChallengeParam: ChallengeParam.md
  - Color: Color.md
  - Console: Console.md
  - DailyChallenge: DailyChallenge.md
  - Entity:
    - Entity: Entity.md
    - EntityFamiliar: EntityFamiliar.md
    - EntityNPC: EntityNPC.md
    - EntityPlayer: EntityPlayer.md
    - EntityPickup: EntityPickup.md
    - EntitySlot: EntitySlot.md
  - Font: Font.md
  - Game: Game.md
  - GridEntity:
    - GridEntity: GridEntity.md
    - GridEntityRock: GridEntityRock.md
  - History: History.md
  - HistoryItem: HistoryItem.md
  - HUD: HUD.md
  - ImGui: ImGui.md
  - Isaac: Isaac.md
  - ItemOverlay: ItemOverlay.md
  - ItemPool: ItemPool.md
  - LayerState: LayerState.md
  - Level: Level.md
  - LevelGeneratorEntry: LevelGeneratorEntry.md
  - MainMenu: MainMenu.md
  - Minimap: Minimap.md
  - MultiShotParams: MultiShotParams.md
  - MusicManager: MusicManager.md
  - NightmareScene: NightmareScene.md
  - NullFrame: NullFrame.md
  - PersistentGameData: PersistentGameData.md
  - ProceduralItemManager: ProceduralItemManager.md
  - PlayerHUD: PlayerHUD.md
  - PlayerManager: PlayerManager.md
  - PocketItem: PocketItem.md
  - ProjectileParams: ProjectileParams.md
  - RNG: RNG.md
  - Room: Room.md
  - RoomConfigHolder: RoomConfigHolder.md
  - RoomTransition: RoomTransition.md
  - Sprite: Sprite.md
  - StageTransition: StageTransition.md
  - Weapon: Weapon.md
  - XMLData: XMLData.md
- Changes:
  - General: changes/General.md
  - Debugging: changes/Debugging.md
  - UI: changes/UI.md
- XML:
  - players.xml: xml/players.md
- Lua 5.4 Docs: https://www.lua.org/manual/5.4/
- Custom Rendering: CustomRendering.md
plugins:
- search:
    separator: "[\\s\\-\\.\\_\\\xB7]+"
repo_name: IsaacZHL/REPENTOGON
repo_url: https://github.com/IsaacZHL/REPENTOGON
site_name: 'BoI: REPENTOGON Docs'
site_url: https://repentogon.com
theme:
  favicon: img/favicon.ico
  features:
  - search.suggest
  - search.highlight
  - search.share
  - navigation.tabs
  - navigation.instant
  - navigation.top
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - accent: amber
    media: '(prefers-color-scheme: dark)'
    primary: amber
    scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
use_directory_urls: false
