copyright: Copyright &copy; 2023 REPENTOGON developers
edit_uri: edit/main/documentation/docs/
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/IsaacZHL/REPENTOGON
    name: REPENTOGON source code and documentation
  version:
    default: rep
    provider: mike
extra_css:
- css/custom.css
extra_javascript:
- https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js
- https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
- js/tablesort.number.min.js
- js/customJS.js
- js/jquery.mark.min.js
markdown_extensions:
- toc:
    permalink: "\u2693\uFE0E"
    toc_depth: 3
- pymdownx.highlight:
    linenums: true
- pymdownx.superfences:
    custom_fences:
    - class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
      name: mermaid
- pymdownx.inlinehilite
- pymdownx.snippets:
    check_paths: true
    url_download: true
- admonition
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
    emoji_index: !!python/name:materialx.emoji.twemoji ''
- pymdownx.tabbed:
    alternate_style: true
- attr_list
nav:
- Home: index.md
- Docs:
  - Home: index.md
  - Enums:
    - Renderer:
      - GLSLType: enums/GLSLType.md
      - ShaderType: enums/ShaderType.md
    - Achievement: enums/Achievement.md
    - AnimRenderFlags: enums/AnimRenderFlags.md
    - AnnouncerVoiceMode: enums/AnnouncerVoiceMode.md
    - AutocompleteType: enums/AutocompleteType.md
    - BagOfCraftingPickup: enums/BagOfCraftingPickup.md
    - BitwiseDebugFlag: enums/BitwiseDebugFlag.md
    - BossType: enums/BossType.md
    - CameraStyle: enums/CameraStyle.md
    - CompletionType: enums/CompletionType.md
    - ConsoleFont: enums/ConsoleFont.md
    - DebugFlag: enums/DebugFlag.md
    - DialogButtons: enums/DialogButtons.md
    - DialogIcons: enums/DialogIcons.md
    - DialogReturn: enums/DialogReturn.md
    - Dimension: enums/Dimension.md
    - DipSubType: enums/DipSubType.md
    - Ending: enums/Ending.md
    - EntityPoopVariant: enums/EntityPoopVariant.md
    - EventCounter: enums/EventCounter.md
    - ExtraHudStyle: enums/ExtraHudStyle.md
    - FadeoutTarget: enums/FadeoutTarget.md
    - FollowerPriority: enums/FollowerPriority.md
    - Giantbook: enums/Giantbook.md
    - GridPoopVariant: enums/GridPoopVariant.md
    - HealthType: enums/HealthType.md
    - ImGuiCallback: enums/ImGuiCallback.md
    - ImGuiColor: enums/ImGuiColor.md
    - ImGuiData: enums/ImGuiData.md
    - ImGuiElement: enums/ImGuiElement.md
    - ItemAnim: enums/ItemAnim.md
    - KnifeSubType: enums/KnifeSubType.md
    - KnifeVariant: enums/KnifeVariant.md
    - Language: enums/Language.md
    - LineCheckMode: enums/LineCheckMode.md
    - MainMenuType: enums/MainMenuType.md
    - ModCallbacks: enums/ModCallbacks.md
    - MouseButton: enums/MouseButton.md
    - NullPickupSubType: enums/NullPickupSubType.md
    - PauseMenuStates: enums/PauseMenuStates.md
    - PedestalType: enums/PedestalType.md
    - PillCardSlot: enums/PillCardSlot.md
    - PlayerVariant: enums/PlayerVariant.md
    - PocketItemType: enums/PocketItemType.md
    - PressurePlateVariant: enums/PressurePlateVariant.md
    - ProceduralEffectActionType: enums/ProceduralEffectActionType.md
    - ProceduralEffectConditionType: enums/ProceduralEffectConditionType.md
    - ProjectileMode: enums/ProjectileMode.md
    - RetractingSpikesVariant: enums/RetractingSpikesVariant.md
    - RoomSubType: enums/RoomSubType.md
    - SlotVariant: enums/SlotVariant.md
    - StbGridType: enums/StbGridType.md
    - StbPoopSubType: enums/StbPoopSubType.md
    - StbRailVariant: enums/StbRailVariant.md
    - StbRockSubType: enums/StbRockSubType.md
    - StbTeleporterSubType: enums/StbTeleporterSubType.md
    - StbType: enums/StbType.md
    - TaintedMarksGroup: enums/TaintedMarksGroup.md
    - TeleporterVariant: enums/TeleporterVariant.md
    - WeaponModifier: enums/WeaponModifier.md
    - WispSubType: enums/WispSubType.md
    - XMLNode: enums/XMLNode.md
  - Ambush: Ambush.md
  - Backdrop: Backdrop.md
  - Camera: Camera.md
  - ChallengeParam: ChallengeParam.md
  - Color: Color.md
  - ColorModifier: ColorModifier.md
  - Console: Console.md
  - DailyChallenge: DailyChallenge.md
  - Debug: Debug.md
  - Entity:
    - Entity: Entity.md
    - EntityFamiliar: EntityFamiliar.md
    - EntityLaser: EntityLaser.md
    - EntityNPC: EntityNPC.md
    - EntityPlayer: EntityPlayer.md
    - EntityPickup: EntityPickup.md
    - EntitySlot: EntitySlot.md
  - Font: Font.md
  - FXParams: FXParams.md
  - Game: Game.md
  - GridEntity:
    - GridEntity: GridEntity.md
    - GridEntityRock: GridEntityRock.md
  - History: History.md
  - HistoryItem: HistoryItem.md
  - HUDs:
    - DebugRenderer: DebugRenderer.md
    - HUD: HUD.md
    - Minimap: Minimap.md
    - PlayerHUD: PlayerHUD.md
    - PlayerHUDHeart: PlayerHUDHeart.md
  - ImGui: ImGui.md
  - Isaac: Isaac.md
  - ItemConfig - PillEffect: ItemConfig_PillEffect.md
  - ItemOverlay: ItemOverlay.md
  - ItemPool: ItemPool.md
  - Level: Level.md
  - LevelGenerator:
    - LevelGenerator: LevelGenerator.md
    - LevelGeneratorEntry: LevelGeneratorEntry.md
    - LevelGeneratorRoom: LevelGeneratorRoom.md
  - Menus:
    - MenuManager: menus/MenuManager.md
    - BestiaryMenu: menus/BestiaryMenu.md
    - ChallengeMenu: menus/ChallengeMenu.md
    - CharacterMenu: menus/CharacterMenu.md
    - CollectionMenu: menus/CollectionMenu.md
    - ControllerSelectMenu: menus/ControllerSelectMenu.md
    - CustomChallengeMenu: menus/CustomChallengeMenu.md
    - CutscenesMenu: menus/CutscenesMenu.md
    - DailyChallengeMenu: menus/DailyChallengeMenu.md
    - KeyConfigMenu: menus/KeyConfigMenu.md
    - MainMenu: menus/MainMenu.md
    - ModsMenu: menus/ModsMenu.md
    - OptionsMenu: menus/OptionsMenu.md
    - SaveMenu: menus/SaveMenu.md
    - SpecialSeedsMenu: menus/SpecialSeedsMenu.md
    - StatsMenu: menus/StatsMenu.md
    - TitleMenu: menus/TitleMenu.md
  - MultiShotParams: MultiShotParams.md
  - MusicManager: MusicManager.md
  - NightmareScene: NightmareScene.md
  - Options: Options.md
  - PersistentGameData: PersistentGameData.md
  - Procedural Items:
    - ProceduralEffect: ProceduralEffect.md
    - ProceduralItem: ProceduralItem.md
    - ProceduralItemManager: ProceduralItemManager.md
  - PlayerManager: PlayerManager.md
  - PocketItem: PocketItem.md
  - ProjectileParams: ProjectileParams.md
  - Rendering:
    - Beam: Beam.md
    - BlendMode: BlendMode.md
    - Capsule: renderer/Capsule.md
    - DestinationQuad: renderer/DestinationQuad.md
    - GLSLValue: renderer/GLSLValue.md
    - Image: renderer/Image.md
    - Pipeline: renderer/Pipeline.md
    - Renderer: renderer/Renderer.md
    - RendererSet: renderer/RendererSet.md
    - Shader: renderer/Shader.md
    - SourceQuad: renderer/SourceQuad.md
    - Shape: renderer/Shape.md
    - Transformer: renderer/Transformer.md
    - Vertex: renderer/Vertex.md
    - VertexBuffer: renderer/VertexBuffer.md
    - VertexDescriptor: renderer/VertexDescriptor.md
  - RNG: RNG.md
  - Room: Room.md
  - RoomConfig:
    - RoomConfigHolder: RoomConfigHolder.md
    - RoomConfigRoom: RoomConfigRoom.md
    - RoomDescriptor: RoomDescriptor.md
    - EntitiesSaveState: EntitiesSaveState.md
    - EntitiesSaveStateVector: EntitiesSaveStateVector.md
  - RoomTransition: RoomTransition.md
  - ScoreSheet: ScoreSheet.md
  - Sprite:
    - AnimationData: AnimationData.md
    - AnimationFrame: AnimationFrame.md
    - AnimationLayer: AnimationLayer.md
    - AnimationState: AnimationState.md
    - LayerState: LayerState.md
    - NullFrame: NullFrame.md
    - Sprite: Sprite.md
  - StageTransition: StageTransition.md
  - Weapon: Weapon.md
  - WeightedOutcomePicker: WeightedOutcomePicker.md
  - XMLData: XMLData.md
- Changes:
  - General: changes/General.md
  - Debugging: changes/Debugging.md
  - UI: changes/UI.md
- XML:
  - players.xml: xml/players.md
- Lua 5.4 Docs: https://www.lua.org/manual/5.4/
- Custom Rendering: renderer/CustomRendering.md
plugins:
- search:
    separator: "[\\s\\-\\.\\_\\\xB7]+"
repo_name: IsaacZHL/REPENTOGON
repo_url: https://github.com/IsaacZHL/REPENTOGON
site_name: 'BoI: REPENTOGON Docs'
site_url: https://repentogon.com
theme:
  custom_dir: overrides
  favicon: img/favicon.ico
  features:
  - search.suggest
  - search.highlight
  - search.share
  - navigation.tabs
  - navigation.instant
  - navigation.top
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - accent: amber
    media: '(prefers-color-scheme: dark)'
    primary: amber
    scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
use_directory_urls: false
