copyright: Copyright &copy; 2023 REPENTOGON developers
edit_uri: edit/main/documentation/docs/
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/IsaacZHL/IsaacZHL
    name: REPENTOGON source code and documentation
  version:
    default: rep
    provider: mike
extra_css:
- css/custom.css
extra_javascript:
- https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js
- https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
- js/tablesort.number.min.js
- js/customJS.js
- js/jquery.mark.min.js
markdown_extensions:
- toc:
    permalink: "\u2693\uFE0E"
    toc_depth: 3
- pymdownx.highlight:
    linenums: true
- pymdownx.superfences:
    custom_fences:
    - class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
      name: mermaid
- pymdownx.inlinehilite
- pymdownx.snippets:
    check_paths: true
    url_download: true
- admonition
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
    emoji_index: !!python/name:materialx.emoji.twemoji ''
- pymdownx.tabbed:
    alternate_style: true
- attr_list
nav:
- Home: index.md
- Docs:
  - Home: index.md
  - Enums:
    - Achievement: enums/Achievement.md
    - BossType: enums/BossType.md
    - Dimension: enums/Dimension.md
    - EntityPoopVariant: enums/EntityPoopVariant.md
    - EventCounter: enums/EventCounter.md
    - FollowerPriority: enums/FollowerPriority.md
    - GridPoopVariant: enums/GridPoopVariant.md
    - HealthType: enums/HealthType.md
    - KnifeSubType: enums/KnifeSubType.md
    - KnifeVariant: enums/KnifeVariant.md
    - LineCheckMode: enums/LineCheckMode.md
    - MainMenu: enums/MainMenu.md
    - ModCallbacks: enums/ModCallbacks.md
    - NullPickupSubType: enums/NullPickupSubType.md
    - PillCardSlot: enums/PillCardSlot.md
    - PlayerVariant: enums/PlayerVariant.md
    - PressurePlateVariant: enums/PressurePlateVariant.md
    - ProjectileMode: enums/ProjectileMode.md
    - RetractingSpikesVariant: enums/RetractingSpikesVariant.md
    - RoomSubType: enums/RoomSubType.md
    - SlotVariant: enums/SlotVariant.md
    - StbGridType: enums/StbGridType.md
    - StbPoopSubType: enums/StbPoopSubType.md
    - StbRailVariant: enums/StbRailVariant.md
    - StbRockSubType: enums/StbRockSubType.md
    - StbTeleporterSubType: enums/StbTeleporterSubType.md
    - StbType: enums/StbType.md
    - TeleporterVariant: enums/TeleporterVariant.md
  - Ambush: Ambush.md
  - Camera: Camera.md
  - Console: Console.md
  - Entity:
    - Entity: Entity.md
    - EntityNPC: EntityNPC.md
    - EntityPlayer: EntityPlayer.md
    - EntityPickup: EntityPickup.md
    - EntitySlot: EntitySlot.md
  - Game: Game.md
  - Isaac: Isaac.md
  - Level: Level.md
  - LevelGeneratorEntry: LevelGeneratorEntry.md
  - MultiShotParams: MultiShotParams.md
  - PersistentGameData: PersistentGameData.md
  - PlayerManager: PlayerManager.md
  - RNG: RNG.md
  - Room: Room.md
  - RoomConfigHolder: RoomConfigHolder.md
  - Sprite: Sprite.md
- Lua 5.3 Docs: https://www.lua.org/manual/5.3/
plugins:
- search:
    separator: "[\\s\\-\\.\\_\\\xB7]+"
repo_name: IsaacZHL/IsaacZHL
repo_url: https://github.com/IsaacZHL/IsaacZHL
site_name: 'BoI: REPENTOGON Docs'
site_url: https://repentogon.com
theme:
  favicon: img/favicon.ico
  features:
  - search.suggest
  - search.highlight
  - search.share
  - navigation.tabs
  - navigation.instant
  - navigation.top
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - accent: amber
    media: '(prefers-color-scheme: dark)'
    primary: amber
    scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
use_directory_urls: false
