name: 'Documentation CI + CD'

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - repentogon/resources/scripts/enums_ex.lua
            - docs/**
permissions:
  contents: write

jobs:
    enums_update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
                cache: 'pip' # caching pip dependencies
            - run: pip install -r ./tools/requirements.txt
            - name: Convert enums to mkdocs
              run: python ./tools/enums2mkdocs.py
    code_checks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2
            - name: Install Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: npm install @actions/core
              
            - name: Run code checks
              run: node ./docs/scripts/code_checks.js
              shell: bash
              
    deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Install Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.x

            - uses: oleksiyrudenko/gha-git-credentials@v2-latest
              with:
                  token: '${{ secrets.GITHUB_TOKEN }}'

            - name: Install PIP packages
              run: |
                   pip install -r ./docs/requirements.txt
                   
            - name: Deploy Documentation
              if:   github.event_name == 'push' && github.ref == 'refs/heads/main'
              run: |
                   cd ./docs
                   mkdocs gh-deploy --force
