name: 'Documentation CI + CD'

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - repentogon/resources/scripts/enums_ex.lua
            - docs/**

jobs:
    enums_update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
                cache: 'pip' # caching pip dependencies
            - run: pip install -r ./tools/requirements.txt
            - name: Convert enums to mkdocs
              run: python ./tools/enums2mkdocs.py
    code_checks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2
            - name: Install Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: npm install @actions/core
              
            - name: Run code checks
              run: node ./docs/scripts/code_checks.js
              shell: bash